# Generated by Django 4.0.4 on 2022-09-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostMod',
        ),
    ]
